# Generated by Django 5.2 on 2025-05-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoicemaster',
            name='sales_invoice_total',
        ),
        migrations.AlterField(
            model_name='salesinvoicemaster',
            name='sales_transport_charges',
            field=models.FloatField(default=0),
        ),
    ]
