# Generated by Django 5.2 on 2025-05-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_salesinvoicemaster_sales_invoice_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_batch_no', models.CharField(max_length=20)),
                ('rate_A', models.FloatField(default=0.0)),
                ('rate_B', models.FloatField(default=0.0)),
                ('rate_C', models.FloatField(default=0.0)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('productid', 'product_batch_no'), name='unique_productid_product_batch_no')],
            },
        ),
    ]
