# Generated by Django 5.2 on 2025-05-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saleratemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpurchasemaster',
            name='return_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='returnsalesmaster',
            name='return_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='returnsalesmaster',
            name='return_sale_calculation_mode',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
    ]
