# Generated by Django 5.2 on 2025-05-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_returnpurchasemaster_return_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='rate_A',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='rate_B',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='rate_C',
        ),
    ]
