# Generated by Django 5.2 on 2025-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productmaster_rate_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='product_barcode',
            field=models.CharField(blank=True, help_text='Product barcode for scanning', max_length=50, null=True, unique=True),
        ),
    ]
