# Generated by Django 5.2 on 2025-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productmaster_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='product_expiry',
            field=models.CharField(help_text='Format: MM-YYYY', max_length=7),
        ),
        migrations.AlterField(
            model_name='returnpurchasemaster',
            name='returnproduct_expiry',
            field=models.CharField(help_text='Format: MM-YYYY', max_length=7),
        ),
        migrations.AlterField(
            model_name='returnsalesmaster',
            name='return_product_expiry',
            field=models.CharField(help_text='Format: MM-YYYY', max_length=7),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='product_expiry',
            field=models.CharField(help_text='Format: MM-YYYY', max_length=7),
        ),
    ]
