# Generated by Django 4.2.16 on 2025-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_invoice_number_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='customer_food_license_no',
            field=models.CharField(blank=True, default='NA', max_length=30),
        ),
    ]
