# Generated by Django 4.2.16 on 2025-09-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customermaster_customer_food_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
