# Generated by Django 5.2.6 on 2025-10-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_inventory_indexes'),
        ('core', '0012_add_finance_models'),
    ]

    operations = [
    ]
