# Generated by Django 4.2.16 on 2025-10-03 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20251003_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receiptmaster',
            options={},
        ),
        migrations.RemoveField(
            model_name='paymentmaster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentmaster',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='receiptmaster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receiptmaster',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='scroll_no',
            field=models.CharField(blank=True, help_text='Manual scroll number for invoice tracking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoicemaster'),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliermaster'),
        ),
        migrations.AddField(
            model_name='receiptmaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customermaster'),
        ),
        migrations.AddField(
            model_name='receiptmaster',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salesinvoicemaster'),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='receipt_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='receipt_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='receipt_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='receipt_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='paymentmaster',
            table=None,
        ),
        migrations.AlterModelTable(
            name='receiptmaster',
            table=None,
        ),
    ]
