# Generated by Django 5.2.6 on 2025-10-06 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_scroll_no_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsalesinvoicemaster',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
