# Generated by Django 5.2.6 on 2025-10-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_returnsalesinvoicemaster_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsalesinvoicemaster',
            name='sales_invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.salesmaster'),
        ),
    ]
