# Generated by Django 5.2.6 on 2025-10-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_returnsalesinvoicemaster_sales_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='web_user',
            name='user_isactive',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
