# Generated by Django 5.2.6 on 2025-10-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_enhanced_sales_return_models"),
    ]

    operations = []
