# Generated by Django 5.2.6 on 2025-10-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_enhanced_sales_return_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enhancedsalesreturn',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='enhancedsalesreturn',
            name='original_invoice',
        ),
        migrations.RemoveField(
            model_name='enhancedsalesreturnitem',
            name='sales_return',
        ),
        migrations.RemoveField(
            model_name='enhancedsalesreturnitem',
            name='original_sale_item',
        ),
        migrations.RemoveField(
            model_name='enhancedsalesreturnitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='SalesReturnApproval',
        ),
        migrations.DeleteModel(
            name='EnhancedSalesReturn',
        ),
        migrations.DeleteModel(
            name='EnhancedSalesReturnItem',
        ),
    ]
