# Generated by Django 5.2.6 on 2025-10-11 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_returnpurchasemaster_returnproduct_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='sale_entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
