# Generated by Django 5.2.6 on 2025-10-11 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_salesmaster_sale_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='purchase_entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
