# Generated by Django 5.2.6 on 2025-10-11 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_returnsalesinvoicepaid_return_sales_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsalesmaster',
            name='return_sale_entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
