# Generated by Django 5.2.6 on 2025-10-11 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_returnsalesinvoicemaster_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemaster',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
