# Generated by Django 5.2.6 on 2025-10-11 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_invoicemaster_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepaid',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
