# Generated by Django 5.2.6 on 2025-10-11 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_invoicepaid_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productratemaster',
            name='rate_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
