# Generated by Django 5.2.6 on 2025-10-11 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_productratemaster_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninvoicemaster',
            name='returninvoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
