# Generated by Django 5.2.6 on 2025-10-11 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_returninvoicemaster_returninvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturninvoicepaid',
            name='pr_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
