# Generated by Django 5.2.6 on 2025-10-11 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_purchasereturninvoicepaid_pr_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnpurchasemaster',
            name='returnpurchase_entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
