# Generated by Django 5.2.6 on 2025-10-11 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_returnpurchasemaster_returnpurchase_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmaster',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
