# Generated by Django 5.2.6 on 2025-10-11 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_paymentmaster_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmaster',
            name='receipt_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
