# Generated by Django 5.2.6 on 2025-10-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_receiptmaster_receipt_date'),
        ('core', '0036_convert_sales_payment_datetime_to_date'),
    ]

    operations = [
    ]
