# Generated by Django 5.2.6 on 2025-10-14 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20251014_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsalesinvoicepaid',
            name='return_sales_payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
